services:
  - type: web
    name: speechtospeech
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      apt-get install -y portaudio19-dev  

      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT run:app 
