services:
  - type: web
    name: speechtospeech
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        portaudio19-dev \
        ffmpeg \
        gcc \
        libasound2-dev \
        libportaudio2 \
        libportaudiocpp0

      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT run:app
